### ISSUE TITLE
오피스 렌즈 테스트케이스

### ISSUE THREAD

**Issue by jeonyung1107** [jeonyung1107/Scanner#3]
오피스렌즈를 이용해서 테스트 케이스를 생성하겠습니다.

**Comment by becxer** [comment]
이미지 similarity 를 구할때 아래 코드 참고하시면 좋을것 같습니다.

언어별 유사도 코드 : https://rosettacode.org/wiki/Percentage_difference_between_images
안드로이드 유사도 비교 : https://stackoverflow.com/questions/14853989/opencv-image-comparison-in-android

**Comment by smilu97** [comment]
안드로이드에 비의존적인 테스트코드를 작성하면 편할 것 같아요.

**Comment by ExcelsiorCJH** [comment]
Python 이긴하나 외곽 추출 관련해서 여기 참고하시면 도움될 듯해요
https://docs.opencv.org/3.1.0/dd/d49/tutorial_py_contour_features.html

**Comment by becxer** [comment]
안드로이드에서 동작 시키지말고 Java 로만 따로 동작시켜도 같은 문제가 발생하는지 확인해보면 
안드로이드 문제인지 opencv 문제인지 확실할거 같습니다.
