### ISSUE TITLE
Thread 문제 해결

### ISSUE THREAD

**Issue by jeonyung1107** [jeonyung1107/Scanner#5]
인식 -> 촬영 단계에서 백그라운드 스레드에 문제가 발생하고있습니다.
해결하겠습니다.

**Comment by smilu97** [comment]
콜 스택이 안 뜨는 거는
try catch 에서 잡혔는데 printStack 함수가 호출 안되는 게 아닐까요?

**Comment by becxer** [comment]
안드로이드에서 동작 시키지말고 Java 로만 따로 동작시켜도 같은 문제가 발생하는지 확인해보면
안드로이드 문제인지 opencv 문제인지 확실할거 같습니다.

**Comment by ExcelsiorCJH** [comment]
Python 이긴하나 외곽 추출 관련해서 여기 참고하시면 도움될 듯해요
Contour Approximation 관련 내용입니다 :-)
https://docs.opencv.org/3.1.0/dd/d49/tutorial_py_contour_features.html

**Comment by jungwon1413** [comment]
잘은 모르겠지만 Multi Threading에 대해 알면 도움이 되지 않을까 싶을까요?

**Comment by PreNa** [comment]
쓰레드는 고통입니다.. 파이팅이요

**Comment by happymman** [comment]
파이팅이용!~ㅎㅎ

**Comment by jeonyung1107** [comment]
문제 해결 됐습니다.
촬영 이후 openCV MatofPoint 객체를 전달하는 과정에서 문제가 있었습니다.
